/*****************************************************************************

    Copyright (C) 2002-2018 Codeplay Software Limited
    All Rights Reserved.

    Codeplay's ComputeCpp

*******************************************************************************/

/**
  @file sycl_undefine.h

  @brief This file undefines all macros defined in the header files that could
  not be undefined before.
*/

#ifndef RUNTIME_INCLUDE_SYCL_UNDEFINE_H_
#define RUNTIME_INCLUDE_SYCL_UNDEFINE_H_

#undef COMPUTECPP_ACCESSOR_WINDOWS_ALIGNMENT
#undef COMPUTECPP_ACCESSOR_LINUX_ALIGNMENT
#undef COMPUTECPP_ASSERT
#undef COMPUTECPP_ASSERT_HELPER
#undef COMPUTECPP_BUILTIN_UNREACHABLE
#undef COMPUTECPP_CE
#undef COMPUTECPP_PE
#undef COMPUTECPP_ABI_CONSTEXPR
#undef COMPUTECPP_ABI_CONSTEXPR_HELPER
#undef COMPUTECPP_CL_API_CALL
#undef COMPUTECPP_CL_ASP_SUBGROUP_LOCAL
#undef COMPUTECPP_CL_ASP_ADDRESS
#undef COMPUTECPP_CL_ASP_CONSTANT
#undef COMPUTECPP_CL_ASP_GLOBAL
#undef COMPUTECPP_CL_ASP_LOCAL
#undef COMPUTECPP_CL_ASP_PRIVATE
#undef COMPUTECPP_CL_ERROR_CODE
#undef COMPUTECPP_CL_ERROR_CODE_MSG
#undef COMPUTECPP_CLANG_FORMAT_BARRIER
#undef COMPUTECPP_CONSTEXPR_CPP14
#undef COMPUTECPP_CONSTEXPR_CPP14_HELPER
#undef COMPUTECPP_CONSTEXPR_EXPORT
#undef COMPUTECPP_CLK_GLOBAL_MEM_FENCE
#undef COMPUTECPP_CLK_LOCAL_MEM_FENCE
#undef COMPUTECPP_CONVERT_ATTR
#undef COMPUTECPP_CONVERT_ATTR_PLACEHOLDER
#undef COMPUTECPP_CONVERT_ATTR_STREAM
#undef COMPUTECPP_CONVERT_ATTR_SAMPLER
#undef COMPUTECPP_CONVERT_ATTR_USM_WRAPPER
#undef COMPUTECPP_DEFINE_SYCL_INFO_HANDLER
#undef COMPUTECPP_DEFINE_SYCL_INFO_HOST
#undef COMPUTECPP_DEFINE_SYCL_INFO_PARAMETER
#undef COMPUTECPP_DEPRECATED_API
#undef COMPUTECPP_HOST_COMPILER_STRING
#undef COMPUTECPP_ENV_32
#undef COMPUTECPP_ENV_64
#undef COMPUTECPP_ENABLE_IF
#undef COMPUTECPP_ENABLE_VAL
#undef COMPUTECPP_GCC_PRE_4_9
#undef COMPUTECPP_GET_INFO_INSTANTIATION
#undef COMPUTECPP_GET_INFO_SPECIALIZATION_DECL
#undef COMPUTECPP_GET_INFO_SPECIALIZATION_DEF
#undef COMPUTECPP_IF_CONSTEXPR
#undef COMPUTECPP_IF_CONSTEXPR_HELPER
#undef COMPUTECPP_INDEX_ARRAY_SELF_ASSIGN_OP
#undef COMPUTECPP_LINUX
#undef COMPUTECPP_LOG
#undef COMPUTECPP_NOT_IMPLEMENTED
#undef COMPUTECPP_PRIVATE_MEMORY_ATTR
#undef COMPUTECPP_PTR_SIZE
#undef COMPUTECPP_TEST_OVERRIDE
#undef COMPUTECPP_TEST_VIRTUAL
#undef COMPUTECPP_THREAD_LOCAL
#undef COMPUTECPP_UNREACHABLE
#undef COMPUTECPP_UNREACHABLE_HELPER
#undef COMPUTECPP_VALID_KERNEL_ARG_IF
#undef COMPUTECPP_WINDOWS

#undef COMPUTECPP_BUILTIN_INVOKE3
#undef COMPUTECPP_BUILTIN_INVOKE2
#undef COMPUTECPP_BUILTIN_INVOKE1
#undef COMPUTECPP_BUILTIN_INVOKE_IMPL
#undef COMPUTECPP_CPP_TO_CL
#undef COMPUTECPP_CL_TO_CPP
#undef COMPUTECPP_REQUIRES
#undef COMPUTECPP_REQUIRES_IMPL
#undef COMPUTECPP_DETAIL_NAMESPACE

#ifdef RUNTIME_INCLUDE_GSL_DETAIL_CONTRACTS_H_
#undef COMPUTECPP_EXPECTS
#undef COMPUTECPP_ENSURES
#endif  // RUNTIME_INCLUDE_GSL_DETAIL_CONTRACTS_H_

#endif  // RUNTIME_INCLUDE_SYCL_UNDEFINE_H_
