/*****************************************************************

    Copyright (C) 2002-2018 Codeplay Software Limited
    All Rights Reserved.

    Codeplay's ComputeCpp

********************************************************************/

/*!
  @file version.h

  @brief This file contains some common version related macros.

  This file is generated by CMake, do not modify it.
 */
#ifndef RUNTIME_INCLUDE_SYCL_VERSION_H_
#define RUNTIME_INCLUDE_SYCL_VERSION_H_

#include "SYCL/host_compiler_macros.h"

COMPUTECPP_HOST_CXX_DIAGNOSTIC(push)
COMPUTECPP_CLANG_CXX_DIAGNOSTIC(ignored "-Wreserved-id-macro")

/** Full string version of ComputeCpp, including the edition and date
 */
#define __COMPUTECPP__ "CE 2.7.0 2021/09/27"

COMPUTECPP_HOST_CXX_DIAGNOSTIC(pop)

#define COMPUTECPP_VERSION_MAJOR 2
#define COMPUTECPP_VERSION_MINOR 7
#define COMPUTECPP_VERSION_PATCH 0

/** ComputeCpp version number as a string
 */
#define COMPUTECPP_VERSION_STRING \
  "2.7.0"

/** @cond COMPUTECPP_DEV */

/** @brief Specifies the edition of the ComputeCpp build
*/
#define COMPUTECPP_CE 1

/** COMPUTECPP_DEV @endcond */

#endif /* RUNTIME_INCLUDE_SYCL_VERSION_H_ */
